from __future__ import annotations


KEYWORDS: dict[str, tuple[str, ...]] = {
    "produce": (
        "apfel",
        "äpfel",
        "banane",
        "beeren",
        "birne",
        "champignon",
        "gurke",
        "kartoffel",
        "lauch",
        "möhren",
        "obst",
        "paprika",
        "salat",
        "spargel",
        "tomate",
        "trauben",
        "zwiebel",
    ),
    "dairy": (
        "butter",
        "joghurt",
        "käse",
        "milch",
        "mozzarella",
        "quark",
        "sahne",
        "skyr",
        "weisskäse",
        "weißkäse",
    ),
    "meat_fish": (
        "braten",
        "filet",
        "fisch",
        "forelle",
        "hähnchen",
        "kalb",
        "lachs",
        "mett",
        "rind",
        "salami",
        "schinken",
        "schwein",
        "steak",
        "wurst",
    ),
    "bakery": (
        "back",
        "baguette",
        "brötchen",
        "brot",
        "croissant",
        "kuchen",
        "toast",
    ),
    "pantry": (
        "bohnen",
        "cerealien",
        "chips",
        "eis",
        "kaffee",
        "konserve",
        "mehl",
        "müsli",
        "nudeln",
        "öl",
        "pasta",
        "pesto",
        "reis",
        "sauce",
        "schokolade",
        "suppe",
        "tee",
    ),
    "drinks": (
        "bier",
        "cola",
        "drink",
        "getränk",
        "limonade",
        "saft",
        "sekt",
        "wasser",
        "wein",
    ),
    "household": (
        "batterie",
        "beutel",
        "folie",
        "küche",
        "papier",
        "reiniger",
        "spül",
        "toiletten",
        "wasch",
    ),
    "personal_care": (
        "binden",
        "creme",
        "deo",
        "dusch",
        "kosmetik",
        "pflege",
        "pflaster",
        "rasur",
        "shampoo",
        "seife",
        "tape",
        "zahnpasta",
    ),
    "baby": ("baby", "pampers", "windeln"),
}


def categorize_offer(title: str, brand: str | None = None, description: str | None = None) -> str:
    haystack = " ".join(part for part in (title, brand or "", description or "") if part).casefold()
    for category, words in KEYWORDS.items():
        if any(word in haystack for word in words):
            return category
    return "other"
